// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: ingest/processors/token_transfer/token_transfer_event.proto

package token_transfer

import (
	address "github.com/stellar/go/ingest/address"
	asset "github.com/stellar/go/ingest/asset"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventMeta message
type EventMeta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence  uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	ClosedAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	TxHash          string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	OperationIndex  *uint32                `protobuf:"varint,4,opt,name=operation_index,json=operationIndex,proto3,oneof" json:"operation_index,omitempty"`
	ContractAddress *address.Address       `protobuf:"bytes,5,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EventMeta) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *EventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventMeta) GetOperationIndex() uint32 {
	if x != nil && x.OperationIndex != nil {
		return *x.OperationIndex
	}
	return 0
}

func (x *EventMeta) GetContractAddress() *address.Address {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *address.Address       `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *address.Address       `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescGZIP(), []int{1}
}

func (x *Transfer) GetFrom() *address.Address {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Transfer) GetTo() *address.Address {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Transfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Mint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            *address.Address       `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mint) Reset() {
	*x = Mint{}
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mint) ProtoMessage() {}

func (x *Mint) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mint.ProtoReflect.Descriptor instead.
func (*Mint) Descriptor() ([]byte, []int) {
	return file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescGZIP(), []int{2}
}

func (x *Mint) GetTo() *address.Address {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Mint) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Burn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *address.Address       `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Burn) Reset() {
	*x = Burn{}
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Burn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Burn) ProtoMessage() {}

func (x *Burn) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Burn.ProtoReflect.Descriptor instead.
func (*Burn) Descriptor() ([]byte, []int) {
	return file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescGZIP(), []int{3}
}

func (x *Burn) GetFrom() *address.Address {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Burn) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Clawback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *address.Address       `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clawback) Reset() {
	*x = Clawback{}
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clawback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clawback) ProtoMessage() {}

func (x *Clawback) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clawback.ProtoReflect.Descriptor instead.
func (*Clawback) Descriptor() ([]byte, []int) {
	return file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescGZIP(), []int{4}
}

func (x *Clawback) GetFrom() *address.Address {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Clawback) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Fee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *address.Address       `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fee) Reset() {
	*x = Fee{}
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescGZIP(), []int{5}
}

func (x *Fee) GetFrom() *address.Address {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Fee) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type TokenTransferEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Asset *asset.Asset           `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"` // Asset can be native or issued. For custom tokens, it will be absent
	// Types that are valid to be assigned to Event:
	//
	//	*TokenTransferEvent_Transfer
	//	*TokenTransferEvent_Mint
	//	*TokenTransferEvent_Burn
	//	*TokenTransferEvent_Clawback
	//	*TokenTransferEvent_Fee
	Event         isTokenTransferEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenTransferEvent) Reset() {
	*x = TokenTransferEvent{}
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenTransferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenTransferEvent) ProtoMessage() {}

func (x *TokenTransferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenTransferEvent.ProtoReflect.Descriptor instead.
func (*TokenTransferEvent) Descriptor() ([]byte, []int) {
	return file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescGZIP(), []int{6}
}

func (x *TokenTransferEvent) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TokenTransferEvent) GetAsset() *asset.Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *TokenTransferEvent) GetEvent() isTokenTransferEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TokenTransferEvent) GetTransfer() *Transfer {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetMint() *Mint {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Mint); ok {
			return x.Mint
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetBurn() *Burn {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Burn); ok {
			return x.Burn
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetClawback() *Clawback {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Clawback); ok {
			return x.Clawback
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetFee() *Fee {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Fee); ok {
			return x.Fee
		}
	}
	return nil
}

type isTokenTransferEvent_Event interface {
	isTokenTransferEvent_Event()
}

type TokenTransferEvent_Transfer struct {
	Transfer *Transfer `protobuf:"bytes,3,opt,name=transfer,proto3,oneof"`
}

type TokenTransferEvent_Mint struct {
	Mint *Mint `protobuf:"bytes,4,opt,name=mint,proto3,oneof"`
}

type TokenTransferEvent_Burn struct {
	Burn *Burn `protobuf:"bytes,5,opt,name=burn,proto3,oneof"`
}

type TokenTransferEvent_Clawback struct {
	Clawback *Clawback `protobuf:"bytes,6,opt,name=clawback,proto3,oneof"`
}

type TokenTransferEvent_Fee struct {
	Fee *Fee `protobuf:"bytes,7,opt,name=fee,proto3,oneof"`
}

func (*TokenTransferEvent_Transfer) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Mint) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Burn) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Clawback) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Fee) isTokenTransferEvent_Event() {}

var File_ingest_processors_token_transfer_token_transfer_event_proto protoreflect.FileDescriptor

var file_ingest_processors_token_transfer_token_transfer_event_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x73, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x69, 0x6e,
	0x67, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x02, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x37, 0x0a,
	0x09, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x64, 0x41, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x2c, 0x0a, 0x0f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0e, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x3b, 0x0a,
	0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x6a,
	0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x20, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x04, 0x4d, 0x69,
	0x6e, 0x74, 0x12, 0x20, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x44, 0x0a, 0x04,
	0x42, 0x75, 0x72, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x48, 0x0a, 0x08, 0x43, 0x6c, 0x61, 0x77, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x24,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x43, 0x0a, 0x03,
	0x46, 0x65, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0xe1, 0x02, 0x0a, 0x12, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x52, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x2e, 0x4d, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x74, 0x12,
	0x2a, 0x0a, 0x04, 0x62, 0x75, 0x72, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x42,
	0x75, 0x72, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x62, 0x75, 0x72, 0x6e, 0x12, 0x36, 0x0a, 0x08, 0x63,
	0x6c, 0x61, 0x77, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x43,
	0x6c, 0x61, 0x77, 0x62, 0x61, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x08, 0x63, 0x6c, 0x61, 0x77, 0x62,
	0x61, 0x63, 0x6b, 0x12, 0x27, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x2e, 0x46, 0x65, 0x65, 0x48, 0x00, 0x52, 0x03, 0x66, 0x65, 0x65, 0x42, 0x07, 0x0a, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescOnce sync.Once
	file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescData = file_ingest_processors_token_transfer_token_transfer_event_proto_rawDesc
)

func file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescGZIP() []byte {
	file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescOnce.Do(func() {
		file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescData)
	})
	return file_ingest_processors_token_transfer_token_transfer_event_proto_rawDescData
}

var file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ingest_processors_token_transfer_token_transfer_event_proto_goTypes = []any{
	(*EventMeta)(nil),             // 0: token_transfer.EventMeta
	(*Transfer)(nil),              // 1: token_transfer.Transfer
	(*Mint)(nil),                  // 2: token_transfer.Mint
	(*Burn)(nil),                  // 3: token_transfer.Burn
	(*Clawback)(nil),              // 4: token_transfer.Clawback
	(*Fee)(nil),                   // 5: token_transfer.Fee
	(*TokenTransferEvent)(nil),    // 6: token_transfer.TokenTransferEvent
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*address.Address)(nil),       // 8: address.Address
	(*asset.Asset)(nil),           // 9: asset.Asset
}
var file_ingest_processors_token_transfer_token_transfer_event_proto_depIdxs = []int32{
	7,  // 0: token_transfer.EventMeta.closed_at:type_name -> google.protobuf.Timestamp
	8,  // 1: token_transfer.EventMeta.contract_address:type_name -> address.Address
	8,  // 2: token_transfer.Transfer.from:type_name -> address.Address
	8,  // 3: token_transfer.Transfer.to:type_name -> address.Address
	8,  // 4: token_transfer.Mint.to:type_name -> address.Address
	8,  // 5: token_transfer.Burn.from:type_name -> address.Address
	8,  // 6: token_transfer.Clawback.from:type_name -> address.Address
	8,  // 7: token_transfer.Fee.from:type_name -> address.Address
	0,  // 8: token_transfer.TokenTransferEvent.meta:type_name -> token_transfer.EventMeta
	9,  // 9: token_transfer.TokenTransferEvent.asset:type_name -> asset.Asset
	1,  // 10: token_transfer.TokenTransferEvent.transfer:type_name -> token_transfer.Transfer
	2,  // 11: token_transfer.TokenTransferEvent.mint:type_name -> token_transfer.Mint
	3,  // 12: token_transfer.TokenTransferEvent.burn:type_name -> token_transfer.Burn
	4,  // 13: token_transfer.TokenTransferEvent.clawback:type_name -> token_transfer.Clawback
	5,  // 14: token_transfer.TokenTransferEvent.fee:type_name -> token_transfer.Fee
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_ingest_processors_token_transfer_token_transfer_event_proto_init() }
func file_ingest_processors_token_transfer_token_transfer_event_proto_init() {
	if File_ingest_processors_token_transfer_token_transfer_event_proto != nil {
		return
	}
	file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[0].OneofWrappers = []any{}
	file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes[6].OneofWrappers = []any{
		(*TokenTransferEvent_Transfer)(nil),
		(*TokenTransferEvent_Mint)(nil),
		(*TokenTransferEvent_Burn)(nil),
		(*TokenTransferEvent_Clawback)(nil),
		(*TokenTransferEvent_Fee)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ingest_processors_token_transfer_token_transfer_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ingest_processors_token_transfer_token_transfer_event_proto_goTypes,
		DependencyIndexes: file_ingest_processors_token_transfer_token_transfer_event_proto_depIdxs,
		MessageInfos:      file_ingest_processors_token_transfer_token_transfer_event_proto_msgTypes,
	}.Build()
	File_ingest_processors_token_transfer_token_transfer_event_proto = out.File
	file_ingest_processors_token_transfer_token_transfer_event_proto_rawDesc = nil
	file_ingest_processors_token_transfer_token_transfer_event_proto_goTypes = nil
	file_ingest_processors_token_transfer_token_transfer_event_proto_depIdxs = nil
}
