FORMAT: 1A
HOST: http://localhost:4200/

# Horizon Admin API

The Admin API is optionally published on separate local port and provides access to 
some aspects of server config and settings. It is only enabled if runtime parameter `--admin-port=<port>` is specified.

## Metrics [/metrics]

### Get latest metrics on server runtime [GET]

+ Response 200 (text/plain)

        # HELP go_gc_duration_seconds A summary of the GC invocation durations.
        # TYPE go_gc_duration_seconds summary
        go_gc_duration_seconds{quantile="0"} 2.7834e-05
        go_gc_duration_seconds{quantile="0.25"} 0.000158374
        go_gc_duration_seconds{quantile="0.5"} 0.000334749
        go_gc_duration_seconds{quantile="0.75"} 0.000922251
        go_gc_duration_seconds{quantile="1"} 0.02497575
        go_gc_duration_seconds_sum 2.140231182
        go_gc_duration_seconds_count 7466
        ... many, many more

## Debug [/debug]

### Get golang performance heap dump [GET /pprof/heap]

+ Response 200 (application/octet-stream)

        ... binary
        
### Get golang performance profile dump [GET /pprof/profile]

+ Response 200 (application/octet-stream)

        ... binary        

## Filters [/ingestiong/filters]

### Get Asset Filter Config [GET /asset]

Retrieve the configuration for the Asset Filter.

+ Response 200 (application/json)

        {
            "whitelist": ["4","5","6"],
            "enabled": true,
            "last_modified": 1647121423
        }

### Get Account Filter Config [GET /account]

Retrieve the configuration for the Account Filter.

+ Response 200 (application/json)

        {
            "whitelist": ["4","5","6"],
            "enabled": true,
            "last_modified": 1647121423
        }


### Update the Asset Filter Config [PUT /asset]

Send the new configuration model which will replace current for Asset Filter.

+ Request (application/json)

        {
            "whitelist": ["4","5","6"],
            "enabled": true,
        }

+ Response 200 (application/json)

### Update the Asset Filter Config [PUT /account]

Send the new configuration model which will replace current for Account Filter.

+ Request (application/json)

        {
            "whitelist": ["4","5","6"],
            "enabled": true,
        }

+ Response 200 (application/json)

    