openapi: 3.0.0
info:
  title: Stellar Horizon Async Transaction Submission
  version: "1.0"
paths:
  /transactions_async:
    post:
      summary: Asynchronously submit a transaction to the Stellar network.
      tags:
        - Transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tx:
                  type: string
                  description: A base64 transaction XDR string.
              required:
                - tx
      responses:
        '201':
          description: Transaction has been received by core and is in pending status.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncTransactionSubmissionResponse'
              example: 
                  tx_status: "PENDING"
                  hash: "6cbb7f714bd08cea7c30cab7818a35c510cbbfc0a6aa06172a1e94146ecf0165"

        '400':
          description: Transaction is malformed; transaction submission exception; transaction submission failed; invalid submission status from core; ERROR status from core.
          content:
            application/json:
              schema:
                oneOf: 
                  - $ref: '#/components/schemas/AsyncTransactionSubmissionResponse'
                  - $ref: '#/components/schemas/Problem'
              examples:
                TransactionMalformedExample:
                  summary: Transaction Malformed
                  value:
                    type: "transaction_malformed"
                    title: "Transaction Malformed"
                    status: 400
                    detail: "Horizon could not decode the transaction envelope in this request. A transaction should be an XDR TransactionEnvelope struct encoded using base64. The envelope read from this request is echoed in the `extras.envelope_xdr` field of this response for your convenience."
                    extras:
                      envelope_xdr: ""
                ErrorStatusExample:
                  summary: ERROR Status from core
                  value:
                    error_result_xdr: "AAAAAAAAAGT////7AAAAAA=="
                    tx_status: "ERROR"
                    hash: "6cbb7f714bd08cea7c30cab7818a35c510cbbfc0a6aa06172a1e94146ecf0165"
        '405':
          description: Transaction submission has been disabled for Horizon.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                TransactionSubmissionDisabledExample:
                  summary: Transaction Submission Disabled
                  value:
                    type: "transaction_submission_disabled"
                    title: "Transaction Submission Disabled"
                    status: 403
                    detail: "Transaction submission has been disabled for Horizon. To enable it again, remove env variable DISABLE_TX_SUB."
                    extras:
                      envelope_xdr: ""
        '409':
          description: Transaction is a duplicate of a previously submitted transaction.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncTransactionSubmissionResponse'
              example: 
                  error_result_xdr: ""
                  tx_status: "DUPLICATE"
                  hash: "6cbb7f714bd08cea7c30cab7818a35c510cbbfc0a6aa06172a1e94146ecf0165"
        '500':
          description: Transaction is a duplicate of a previously submitted transaction.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
              examples:
                TransactionFailedExample:
                  summary: Transaction Submission Failed
                  value:
                    type: "transaction_submission_failed"
                    title: "Transaction Submission Failed"
                    status: 500
                    detail: "Could not submit transaction to stellar-core. The `extras.error` field on this response contains further details. Descriptions of each code can be found at: https://developers.stellar.org/api/errors/http-status-codes/horizon-specific/transaction-submission-async/transaction_submission_failed"
                    extras:
                      envelope_xdr: ""
                      error: "Error details here"
                TransactionExceptionExample:
                  summary: Transaction Submission Exception
                  value:
                    type: "transaction_submission_exception"
                    title: "Transaction Submission Exception"
                    status: 500
                    detail: "Received exception from stellar-core. The `extras.error` field on this response contains further details. Descriptions of each code can be found at: https://developers.stellar.org/api/errors/http-status-codes/horizon-specific/transaction-submission-async/transaction_submission_exception"
                    extras:
                      envelope_xdr: ""
                      error: "Exception details here"
        '503':
          description: History DB is stale; core is unavailable for transaction submission.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncTransactionSubmissionResponse'
              examples:
                HistoryDBStaleExample:
                  summary: Historical DB Is Too Stale
                  value:
                    type: "stale_history"
                    title: "Historical DB Is Too Stale"
                    status: 503
                    detail: "This horizon instance is configured to reject client requests when it can determine that the history database is lagging too far behind the connected instance of Stellar-Core or read replica. It's also possible that Stellar-Core is out of sync. Please try again later."
                    extras:
                      envelope_xdr: ""
                TryAgainLaterExample:
                  summary: TRY_AGAIN_LATER Status from core
                  value:
                    tx_status: "TRY_AGAIN_LATER"
                    hash: "6cbb7f714bd08cea7c30cab7818a35c510cbbfc0a6aa06172a1e94146ecf0165"

                  
components:
  schemas:
    AsyncTransactionSubmissionResponse:
      type: object
      properties:
        error_result_xdr:
          type: string
          nullable: true
          description: TransactionResult XDR string which is present only if the submission status from core is an ERROR.
        errorResultXdr:
          type: string
          nullable: true
          description: This field is deprecated, use error_result_xdr instead.
        tx_status:
          type: string
          enum: ["ERROR", "PENDING", "DUPLICATE", "TRY_AGAIN_LATER"]
          description: Status of the transaction submission.
        hash:
          type: string
          description: Hash of the transaction.
    Problem:
      type: object
      properties:
        type:
          type: string
          description: Identifies the problem type.
        title:
          type: string
          description: A short, human-readable summary of the problem type.
        status:
          type: integer
          description: The HTTP status code for this occurrence of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        extras:
          type: object
          additionalProperties: true
          description: Additional details that might help the client understand the error(s) that occurred.
