#! /bin/bash
set -e

if [ "$CGO_ENABLED" = "1" ] 
then
    glide novendor | sed 's/^\./github.com\/stellar\/go/g' | xargs -I {} go test -race {}
else
    glide novendor | sed 's/^\./github.com\/stellar\/go/g' | xargs -I {} go test {}
fi
