#! /bin/bash
set -e

if [ "$CGO_ENABLED" = "1" ] 
then
    glide novendor | sed 's/^\./github.com\/stellar\/go/g' | xargs -I {} go test -race {}
else
    glide novendor | sed 's/^\./github.com\/stellar\/go/g' | xargs -I {} go test {}
fi

#for TEST in $TESTS; do
#    go test -race $TEST
#  else
#    go test $TEST
#  fi
#done
