#! /usr/bin/env bash
set -e

service postgresql start

# Calculate params for AWS Batch
if [ ! -z "$AWS_BATCH_JOB_ARRAY_INDEX" ]; then
	# The batch should have three env variables:
	# * BATCH_START_LEDGER - start ledger of the job, must be equal 1 or a
	#   checkpoint ledger (i + 1) % 64 == 0.
	# * BATCH_SIZE - size of the batch in ledgers, must be multiple of 64!
	# * BRANCH - git branch to build
	#
	# Ex: BATCH_START_LEDGER=63, BATCH_SIZE=64 will create the following ranges:
	# AWS_BATCH_JOB_ARRAY_INDEX=0: [63, 127]
	# AWS_BATCH_JOB_ARRAY_INDEX=1: [127, 191]
	# AWS_BATCH_JOB_ARRAY_INDEX=2: [191, 255]
	# AWS_BATCH_JOB_ARRAY_INDEX=3: [255, 319]
	# ...

	if [ $BATCH_START_LEDGER -eq 1 ]; then
		export FROM=`expr "$BATCH_SIZE" \* "$AWS_BATCH_JOB_ARRAY_INDEX" + "$BATCH_START_LEDGER" - "2"`
		export TO=`expr "$BATCH_SIZE" \* "$AWS_BATCH_JOB_ARRAY_INDEX" + "$BATCH_START_LEDGER" + "$BATCH_SIZE" - "2"`
		if [ $FROM -eq -1 ]; then
			export FROM="1"
		fi
	else
		export FROM=`expr "$BATCH_SIZE" \* "$AWS_BATCH_JOB_ARRAY_INDEX" + "$BATCH_START_LEDGER"`
		export TO=`expr "$BATCH_SIZE" \* "$AWS_BATCH_JOB_ARRAY_INDEX" + "$BATCH_START_LEDGER" + "$BATCH_SIZE"`
	fi
fi

export LEDGER_COUNT=`expr "$TO" - "$FROM" + "1"`

echo "FROM: $FROM TO: $TO"

dump_horizon_db() {
	PGPASSWORD=postgres
	echo "dumping history_effects"
	sudo -u postgres psql -d horizon -t -A -F"," --variable="FETCH_COUNT=10000" -c "select history_effects.history_operation_id, history_effects.order, type, details, history_accounts.address from history_effects left join history_accounts on history_accounts.id = history_effects.history_account_id" >> $1
	echo "dumping history_ledgers"
	sudo -u postgres psql -d horizon -t -A -F"," --variable="FETCH_COUNT=10000" -c "select * from history_ledgers" >> $1
	echo "dumping history_operations"
	sudo -u postgres psql -d horizon -t -A -F"," --variable="FETCH_COUNT=10000" -c "select * from history_operations" >> $1
	echo "dumping history_operation_participants"
	sudo -u postgres psql -d horizon -t -A -F"," --variable="FETCH_COUNT=10000" -c "select history_operation_id, address from history_operation_participants left join history_accounts on history_accounts.id = history_operation_participants.history_account_id" >> $1
	echo "dumping history_trades"
	sudo -u postgres psql -d horizon -t -A -F"," --variable="FETCH_COUNT=10000" -c "select history_trades.history_operation_id, history_trades.order, history_trades.ledger_closed_at, history_trades.offer_id, history_trades.base_is_seller, history_trades.price_n, history_trades.price_d, history_trades.base_offer_id, history_trades.counter_offer_id, baccount.address, caccount.address, basset.asset_type, basset.asset_code, basset.asset_issuer, casset.asset_type, casset.asset_code, casset.asset_issuer from history_trades left join history_accounts baccount on baccount.id = history_trades.base_account_id left join history_accounts caccount on caccount.id = history_trades.counter_account_id left join history_assets basset on basset.id = history_trades.base_asset_id left join history_assets casset on casset.id = history_trades.counter_asset_id limit 1;" >> $1
	echo "dumping history_transactions"
	sudo -u postgres psql -d horizon -t -A -F"," --variable="FETCH_COUNT=10000" -c "select * from history_transactions" >> $1
	echo "dumping history_transaction_participants"
	sudo -u postgres psql -d horizon -t -A -F"," --variable="FETCH_COUNT=10000" -c "select history_transaction_id, address from history_transaction_participants left join history_accounts on history_accounts.id = history_transaction_participants.history_account_id" >> $1
}

stellar-core new-db
stellar-core catchup $TO/$LEDGER_COUNT

# pubnet horizon config
export NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
export HISTORY_ARCHIVE_URLS="https://history.stellar.org/prd/core-live/core_live_001"
export DATABASE_URL="postgres://postgres:postgres@localhost:5432/horizon?sslmode=disable"
export INGEST="false"
export ENABLE_EXPERIMENTAL_INGESTION="true"
export INGEST_FAILED_TRANSACTIONS=true
export STELLAR_CORE_URL="http://localhost:11626"
export STELLAR_CORE_DATABASE_URL="postgres://postgres:postgres@localhost:5432/core?sslmode=disable"

git clone https://github.com/stellar/go.git stellar-go
cd stellar-go
if [ ! -z "$BRANCH" ]; then
	git checkout $BRANCH
fi

/usr/local/go/bin/go build -v ./services/horizon
./horizon db migrate up
./horizon expingest verify-range --from $FROM --to $TO --verify-state

if [ ! -z "$VERIFY_HISTORY" ]; then
	dump_horizon_db "exp_history"

	sudo -u postgres dropdb horizon
	sudo -u postgres createdb horizon

	git checkout h_0.24.1_v2_meta

	/usr/local/go/bin/go build -v ./services/horizon

	export INGEST="true"
	export ENABLE_EXPERIMENTAL_INGESTION="false"

	./horizon db migrate up
	./horizon db reingest range $FROM $TO

	dump_horizon_db "legacy_history"

	diff legacy_history exp_history
fi

echo "OK"
