#!/usr/bin/env bash
set -e

useradd --uid 10011001 --home-dir /home/stellar --no-log-init stellar \
    && mkdir -p /home/stellar \
    && chown -R stellar:stellar /home/stellar

mkdir -p /opt/stellar/bin
mkdir -p /opt/stellar/www
chown -R stellar:stellar /opt/stellar/www
mkdir -p /opt/stellar/postgresql/data
