version: '3'
services:
  core:
    volumes:
      - ./stellar-core-pubnet.cfg:/stellar-core.cfg
  horizon:
    environment:
      - HISTORY_ARCHIVE_URLS=https://history.stellar.org/prd/core-live/core_live_001
      - NETWORK_PASSPHRASE=Public Global Stellar Network ; September 2015
