version: '3'
services:
  core:
    ports:
      # add extra port for history archive server
      - "1570:1570"
    command: /start standalone
    volumes:
      - ./stellar-core-standalone.cfg:/stellar-core.cfg
  horizon:
    environment:
      - HISTORY_ARCHIVE_URLS=http://host.docker.internal:1570
      - NETWORK_PASSPHRASE=Standalone Network ; February 2017
