// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: protos/ingest/ingest_event.proto

package ingest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEvent) Reset() {
	*x = IngestEvent{}
	mi := &file_protos_ingest_ingest_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEvent) ProtoMessage() {}

func (x *IngestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ingest_ingest_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEvent.ProtoReflect.Descriptor instead.
func (*IngestEvent) Descriptor() ([]byte, []int) {
	return file_protos_ingest_ingest_event_proto_rawDescGZIP(), []int{0}
}

func (x *IngestEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_protos_ingest_ingest_event_proto protoreflect.FileDescriptor

var file_protos_ingest_ingest_event_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2f,
	0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x22, 0x31, 0x0a, 0x0b, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x6c, 0x6c, 0x61, 0x72, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x3b, 0x69, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_ingest_ingest_event_proto_rawDescOnce sync.Once
	file_protos_ingest_ingest_event_proto_rawDescData = file_protos_ingest_ingest_event_proto_rawDesc
)

func file_protos_ingest_ingest_event_proto_rawDescGZIP() []byte {
	file_protos_ingest_ingest_event_proto_rawDescOnce.Do(func() {
		file_protos_ingest_ingest_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_ingest_ingest_event_proto_rawDescData)
	})
	return file_protos_ingest_ingest_event_proto_rawDescData
}

var file_protos_ingest_ingest_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_ingest_ingest_event_proto_goTypes = []any{
	(*IngestEvent)(nil), // 0: protos.ingest.IngestEvent
}
var file_protos_ingest_ingest_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_ingest_ingest_event_proto_init() }
func file_protos_ingest_ingest_event_proto_init() {
	if File_protos_ingest_ingest_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_ingest_ingest_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_ingest_ingest_event_proto_goTypes,
		DependencyIndexes: file_protos_ingest_ingest_event_proto_depIdxs,
		MessageInfos:      file_protos_ingest_ingest_event_proto_msgTypes,
	}.Build()
	File_protos_ingest_ingest_event_proto = out.File
	file_protos_ingest_ingest_event_proto_rawDesc = nil
	file_protos_ingest_ingest_event_proto_goTypes = nil
	file_protos_ingest_ingest_event_proto_depIdxs = nil
}
