#! /usr/bin/env bash
set -e

# Validation
if [ -z "$ARCHIVE_TARGET" ]; then
  echo "error: undefined ARCHIVE_TARGET env variable"
  exit 1
fi

if [ -z "$NETWORK" ]; then
  echo "error: undefined NETWORK env variable"
  exit 1
fi

ledgers_per_file="${LEDGERS_PER_FILE:-1}"
files_per_partition="${FILES_PER_PARTITION:-64000}"

# Generate TOML configuration
cat <<EOF > config.toml

[datastore_config]
type = "GCS"

[datastore_config.params]
destination_bucket_path = "${ARCHIVE_TARGET}/${NETWORK}"

[datastore_config.schema]
  ledgers_per_file = $ledgers_per_file
  files_per_partition = $files_per_partition

[stellar_core_config]
  network = "${NETWORK}"
EOF

# Check if START or END variables are set
if [[ -n "$START" || -n "$END" ]]; then
    echo "START: $START END: $END"
    /usr/bin/ledgerexporter scan-and-fill --config-file config.toml --start $START --end $END
else
    echo "Error: No ledger range provided."
    exit 1
fi
