// Code generated by go-bindata. DO NOT EDIT.
// sources:
// migrations/20200309000000-initial-1.sql (162B)
// migrations/20200309000001-initial-2.sql (162B)
// migrations/20200311000000-create-accounts.sql (335B)
// migrations/20200311000001-create-identities.sql (426B)
// migrations/20200311000002-create-auth-methods.sql (925B)

package dbmigrate

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _migrations20200309000000Initial1Sql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x54\xcc\xd1\x0d\xc2\x30\x0c\x04\xd0\xff\x4c\x71\xff\x28\x4c\xc1\x08\x30\x80\x01\xa7\xb5\xd4\xda\x91\x6d\xa8\xb2\x3d\x8a\xf8\x40\x7c\xde\xdd\xd3\xd5\x8a\xeb\x2a\x81\x5d\x16\xa7\x14\x53\x34\xd9\x18\x12\x10\x4d\xd6\xd9\xd0\xb6\x0d\xf0\xde\x73\x80\xf4\x39\x27\x42\x13\x8f\x44\x24\x79\x8a\x2e\xe8\x26\x9a\x68\xe6\xa5\x56\xd8\xcb\x7f\x77\x81\x3b\x37\x73\xc6\xc1\x18\x9c\x58\xe9\xcd\x20\xc4\x63\xe5\x9d\xce\x65\xfa\xd3\x17\x33\x6e\xfd\x3f\x5f\xec\xd0\x52\x3e\x01\x00\x00\xff\xff\xd3\x79\x21\xda\xa2\x00\x00\x00")

func migrations20200309000000Initial1SqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations20200309000000Initial1Sql,
		"migrations/20200309000000-initial-1.sql",
	)
}

func migrations20200309000000Initial1Sql() (*asset, error) {
	bytes, err := migrations20200309000000Initial1SqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/20200309000000-initial-1.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xd1, 0xd1, 0x21, 0xe9, 0x6d, 0xe0, 0xfe, 0xb4, 0x8b, 0x78, 0x2, 0xae, 0x5c, 0xd5, 0x8b, 0x41, 0xb8, 0x4b, 0xaa, 0x3a, 0xea, 0x69, 0xf, 0xf3, 0x2f, 0x6c, 0xae, 0x38, 0x46, 0xb, 0x2, 0xfc}}
	return a, nil
}

var _migrations20200309000001Initial2Sql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x54\xcc\xd1\x0d\xc2\x30\x0c\x04\xd0\xff\x4c\x71\xff\x28\x4c\xc1\x08\x30\x80\x01\xa7\xb5\xd4\xda\x91\x6d\xa8\xb2\x3d\x8a\xf8\x40\x7c\xde\xdd\xd3\xd5\x8a\xeb\x2a\x81\x5d\x16\xa7\x14\x53\x34\xd9\x18\x12\x10\x4d\xd6\xd9\xd0\xb6\x0d\xf0\xde\x73\x80\xf4\x39\x27\x42\x13\x8f\x44\x24\x79\x8a\x2e\xe8\x26\x9a\x68\xe6\xa5\x56\xd8\xcb\x7f\x77\x81\x3b\x37\x73\xc6\xc1\x18\x9c\x58\xe9\xcd\x20\xc4\x63\xe5\x9d\xce\x65\xfa\xd3\x17\x33\x6e\xfd\x3f\x5f\xec\xd0\x52\x3e\x01\x00\x00\xff\xff\xd3\x79\x21\xda\xa2\x00\x00\x00")

func migrations20200309000001Initial2SqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations20200309000001Initial2Sql,
		"migrations/20200309000001-initial-2.sql",
	)
}

func migrations20200309000001Initial2Sql() (*asset, error) {
	bytes, err := migrations20200309000001Initial2SqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/20200309000001-initial-2.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xd1, 0xd1, 0x21, 0xe9, 0x6d, 0xe0, 0xfe, 0xb4, 0x8b, 0x78, 0x2, 0xae, 0x5c, 0xd5, 0x8b, 0x41, 0xb8, 0x4b, 0xaa, 0x3a, 0xea, 0x69, 0xf, 0xf3, 0x2f, 0x6c, 0xae, 0x38, 0x46, 0xb, 0x2, 0xfc}}
	return a, nil
}

var _migrations20200311000000CreateAccountsSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x84\x90\x4f\x4b\xc4\x30\x14\xc4\xef\xef\x53\xcc\xb1\x45\xf7\x13\xf4\x94\xb5\x0f\x37\xd8\xa6\x31\x7d\x61\x77\xbd\x2c\xa1\x09\x52\xd0\x5d\x69\x2b\x7e\x7d\xa1\x68\x09\x5e\x3c\xbe\x3f\xf3\x63\x66\x76\x3b\xdc\xbd\x8f\xaf\x53\x58\x12\xfc\x07\xd1\x83\x63\x25\x0c\x51\xfb\x86\x11\x86\xe1\xf6\x79\x5d\x66\x14\x04\x8c\x11\x7b\xfd\xd8\xb3\xd3\xaa\x81\xe9\x04\xc6\x37\xcd\x3d\x11\x60\x9d\x6e\x95\x3b\xe3\x89\xcf\x28\xc6\x58\xae\xcb\x61\x4a\x61\x49\xf1\x12\x16\x88\x6e\xb9\x17\xd5\x5a\x1c\xb5\x1c\xd6\x11\x2f\x9d\xe1\x8c\x02\xc4\xf4\x96\xfe\xf9\x5f\xb9\x21\xc6\x29\xcd\x33\x84\x4f\xb2\x01\xa8\xac\x36\xeb\xde\xe8\x67\xcf\xd0\xa6\xe6\xd3\x96\xe0\xf2\x2b\xeb\x4c\x96\xca\x5b\xcb\xae\xf8\x39\x95\x25\x8e\x07\x76\x9c\x3b\xd1\xfd\x8a\xaf\x88\xf2\x9e\xea\xdb\xd7\x95\xa8\x76\x9d\xfd\xd3\x53\x45\xdf\x01\x00\x00\xff\xff\x6e\xdf\x97\x68\x4f\x01\x00\x00")

func migrations20200311000000CreateAccountsSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations20200311000000CreateAccountsSql,
		"migrations/20200311000000-create-accounts.sql",
	)
}

func migrations20200311000000CreateAccountsSql() (*asset, error) {
	bytes, err := migrations20200311000000CreateAccountsSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/20200311000000-create-accounts.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x8b, 0x6e, 0x3e, 0x48, 0x39, 0xd6, 0x5, 0xcb, 0xd0, 0x73, 0x7, 0xdc, 0xb8, 0x76, 0x93, 0x8f, 0x2a, 0xde, 0x35, 0xbd, 0x6c, 0xb, 0x1a, 0x1a, 0x3e, 0x3d, 0xf6, 0x79, 0xae, 0x2d, 0xa0, 0xcb}}
	return a, nil
}

var _migrations20200311000001CreateIdentitiesSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x84\x91\xbb\x6e\xc2\x30\x18\x85\xf7\xff\x29\xce\x98\xa8\xf0\x04\x99\x02\xf9\x01\xab\x89\x1d\x39\x46\x40\x97\x28\x8a\xad\xca\x12\x4d\xaa\xe0\xaa\xaf\x5f\x35\xbd\x60\xda\x81\xd1\x3e\xf6\xa7\x73\x59\x2e\xf1\xf0\xe2\x9f\xa7\x2e\x38\xec\x5f\x89\xd6\x9a\x73\xc3\x30\xf9\xaa\x64\x78\xeb\x86\xe0\x83\x77\x17\x24\x04\x74\x7d\x3f\xbe\x0d\xa1\xf5\x16\x2b\xb1\x15\xd2\x40\x2a\x03\xb9\x2f\xcb\x05\x01\x5f\xb7\x0d\x6b\x91\x97\x91\x40\xc0\x46\x69\x16\x5b\x89\x47\x3e\x21\xb9\x42\x52\x68\xde\xb0\x66\xb9\xe6\xe6\x87\x7d\x41\xe2\x6d\xfa\x89\xab\xb5\xa8\x72\x7d\xfa\xfb\x69\x81\x59\x27\xa0\x9f\x5c\x17\x9c\x6d\xbb\x00\x23\x2a\x6e\x4c\x5e\xd5\x38\x08\xb3\x9b\x8f\x78\x52\x92\x6f\xfc\x59\x77\x76\x77\xde\xcf\xdc\x69\x3c\x3b\x18\x3e\x5e\xd3\x51\x9a\xfd\x16\x23\x64\xc1\xc7\xa8\x98\xf6\xdb\x9a\xb7\x50\xf2\xa6\xb0\x38\xe8\x61\xc7\x9a\x63\x07\xa2\x99\xc9\x19\x51\x3c\x40\x31\xbe\x0f\x44\x85\x56\xf5\xbf\x01\x32\xfa\x08\x00\x00\xff\xff\x19\xf3\x50\x25\xaa\x01\x00\x00")

func migrations20200311000001CreateIdentitiesSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations20200311000001CreateIdentitiesSql,
		"migrations/20200311000001-create-identities.sql",
	)
}

func migrations20200311000001CreateIdentitiesSql() (*asset, error) {
	bytes, err := migrations20200311000001CreateIdentitiesSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/20200311000001-create-identities.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xbd, 0xa9, 0xc3, 0xcf, 0x17, 0x59, 0xd4, 0x5f, 0xe8, 0x5f, 0x78, 0xa1, 0x53, 0xa0, 0x20, 0xc7, 0xe1, 0x31, 0xd1, 0xe4, 0x65, 0xea, 0xe7, 0x5, 0xc1, 0xd, 0xe7, 0x14, 0x4a, 0x90, 0x59, 0xb0}}
	return a, nil
}

var _migrations20200311000002CreateAuthMethodsSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x93\xcd\x6e\xdb\x30\x10\x84\xef\x7c\x8a\x45\x2e\xb6\x51\xe5\x09\x74\x52\xe2\x4d\x42\x54\xa2\x04\x4a\x46\xea\x5e\x08\xd6\x5c\xd4\x04\xf4\x63\x48\x54\xdb\xbc\x7d\xa1\x1f\xd7\x92\xff\x5a\xf4\xe8\xd9\xf5\x37\xe4\x8c\xf8\xf8\x08\x9f\x0a\xfb\xbd\xd6\x8e\x60\x73\x60\xec\x59\x62\x90\x21\x64\xdb\x04\x41\xb7\x6e\xaf\x0a\x72\xfb\xca\x28\xf7\x71\x20\x08\x52\x40\xb1\x89\x60\xc9\x00\x16\x8d\xa3\x3c\xd7\xb5\xd2\xc6\xd4\xd4\x34\x0b\xaf\x13\x0f\xfb\xaa\x24\x55\xb6\xc5\x37\xaa\x07\x85\x0a\x6d\xf3\x05\x5b\xf9\x27\x76\xf0\x14\xce\xe0\x4d\x0f\xd4\xbb\x5d\xd5\x96\x4e\x59\x03\x4f\xfc\x95\x8b\x0c\x44\x9c\x81\xd8\x84\x61\xc7\xb1\x86\x4a\x67\xdd\xc7\xcd\x71\xa7\xa6\x28\x79\x10\x4e\x06\x0c\xe0\x25\x96\xc8\x5f\x05\x7c\xc6\x2d\x2c\x4f\x1e\x2b\x90\xf8\x82\x12\xc5\x33\xa6\x47\xeb\x06\x96\xd6\xac\xbc\xdb\x7f\xf2\xa6\xc7\x98\x11\x46\xdd\x52\x73\xbe\xdf\xf3\x12\xc9\xa3\x40\x6e\xef\xf2\xc6\x65\x06\xb0\xab\x49\x3b\x32\x4a\x3b\xc8\x78\x84\x69\x16\x44\x09\xbc\xf3\xec\xad\xff\x09\x5f\x63\x81\xb3\xcb\x1b\xca\xe9\x2f\xfb\x3d\xf7\xa1\x2b\xf1\xe1\xb2\xd6\x29\xeb\x87\xce\x5b\x02\x47\xbf\xdc\x1f\x79\xda\x1d\x17\x6b\xfc\x32\xeb\x4e\x8d\xd7\xb1\x06\x62\x71\xd6\xea\x34\xee\xf7\x37\x94\x38\x3d\x2a\x4f\x7b\xba\xff\x2f\x68\x75\xcc\xe9\xbe\xcb\x59\x3f\xff\x63\xd9\x05\xa2\x86\x10\x2e\x8c\x86\xfc\xbc\x21\xa3\x7b\x78\x36\x7d\x55\xeb\xea\x67\xc9\xd8\x5a\xc6\xc9\x95\x2f\xdf\x1f\x07\xd7\x9e\x9b\xcf\x7e\x07\x00\x00\xff\xff\xa9\x48\x1b\x1b\x9d\x03\x00\x00")

func migrations20200311000002CreateAuthMethodsSqlBytes() ([]byte, error) {
	return bindataRead(
		_migrations20200311000002CreateAuthMethodsSql,
		"migrations/20200311000002-create-auth-methods.sql",
	)
}

func migrations20200311000002CreateAuthMethodsSql() (*asset, error) {
	bytes, err := migrations20200311000002CreateAuthMethodsSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "migrations/20200311000002-create-auth-methods.sql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xfa, 0x31, 0x9a, 0x9c, 0x31, 0x59, 0x2d, 0x3a, 0x55, 0xe0, 0xc5, 0x58, 0x18, 0xd8, 0x9e, 0x1f, 0xa2, 0x4e, 0x4f, 0xf9, 0xdd, 0x55, 0xfd, 0x44, 0xc1, 0x70, 0xf8, 0xfe, 0x8, 0xcc, 0x5b, 0x98}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"migrations/20200309000000-initial-1.sql":           migrations20200309000000Initial1Sql,
	"migrations/20200309000001-initial-2.sql":           migrations20200309000001Initial2Sql,
	"migrations/20200311000000-create-accounts.sql":     migrations20200311000000CreateAccountsSql,
	"migrations/20200311000001-create-identities.sql":   migrations20200311000001CreateIdentitiesSql,
	"migrations/20200311000002-create-auth-methods.sql": migrations20200311000002CreateAuthMethodsSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"migrations": &bintree{nil, map[string]*bintree{
		"20200309000000-initial-1.sql":           &bintree{migrations20200309000000Initial1Sql, map[string]*bintree{}},
		"20200309000001-initial-2.sql":           &bintree{migrations20200309000001Initial2Sql, map[string]*bintree{}},
		"20200311000000-create-accounts.sql":     &bintree{migrations20200311000000CreateAccountsSql, map[string]*bintree{}},
		"20200311000001-create-identities.sql":   &bintree{migrations20200311000001CreateIdentitiesSql, map[string]*bintree{}},
		"20200311000002-create-auth-methods.sql": &bintree{migrations20200311000002CreateAuthMethodsSql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
