// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: ingest/address/address.proto

package address

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// All that you need for identifying an address is the strkey representation
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrKey        string                 `protobuf:"bytes,1,opt,name=str_key,json=strKey,proto3" json:"str_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_ingest_address_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_address_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_ingest_address_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStrKey() string {
	if x != nil {
		return x.StrKey
	}
	return ""
}

var File_ingest_address_address_proto protoreflect.FileDescriptor

var file_ingest_address_address_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x22, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x4b, 0x65, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ingest_address_address_proto_rawDescOnce sync.Once
	file_ingest_address_address_proto_rawDescData = file_ingest_address_address_proto_rawDesc
)

func file_ingest_address_address_proto_rawDescGZIP() []byte {
	file_ingest_address_address_proto_rawDescOnce.Do(func() {
		file_ingest_address_address_proto_rawDescData = protoimpl.X.CompressGZIP(file_ingest_address_address_proto_rawDescData)
	})
	return file_ingest_address_address_proto_rawDescData
}

var file_ingest_address_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ingest_address_address_proto_goTypes = []any{
	(*Address)(nil), // 0: address.Address
}
var file_ingest_address_address_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ingest_address_address_proto_init() }
func file_ingest_address_address_proto_init() {
	if File_ingest_address_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ingest_address_address_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ingest_address_address_proto_goTypes,
		DependencyIndexes: file_ingest_address_address_proto_depIdxs,
		MessageInfos:      file_ingest_address_address_proto_msgTypes,
	}.Build()
	File_ingest_address_address_proto = out.File
	file_ingest_address_address_proto_rawDesc = nil
	file_ingest_address_address_proto_goTypes = nil
	file_ingest_address_address_proto_depIdxs = nil
}
