name: Build Binaries
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  osbuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        service: ["federation", "friendbot", "frontier", "keystored", "loadtest"]
        exclude:  
          - goarch: "386"
            goos: darwin 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'     
      - name: Install Go
        uses: actions/setup-go@v2

      - name: Build the app
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GO111MODULE: on    
        run: |
          go get github.com/hashicorp/golang-lru@v0.5.0
          go build ./...


  frontier-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'  

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: services/frontier/Dockerfile
          build-args: FRONTIER_VERSION=1.0.58
          tags: digitalbits-frontier:1.0.58
          outputs: type=docker,dest=/tmp/image.tar
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        

