name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  golangci-lint:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    if: github.event_name == 'pull_request'
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for new-from-rev option in .golangci.yml
      - name: Run linters & report
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: reviewdog/action-golangci-lint@70498f2d1f75a55ee9a4d719e74e21ed68aebea3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "-c .golangci.yml --allow-parallel-runners"
          level: "warning"
          reporter: github-pr-check
