name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  golangci-lint:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    if: github.event_name == 'pull_request'
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for new-from-rev option in .golangci.yml
      - uses: actions/setup-go@v3
      - name: Run linters & report
        uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc
        with:
          version: v3.2.0
          args: --issues-exit-code=0
          github-token: ${{ secrets.GITHUB_TOKEN }}



