name: "Horizon verify range test job"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
      baseBranch:
        description: 'Base Branch'
        required: false
        default: 'horizon-v2.0.0'
      batchStartLedger:
        description: 'Batch Start Ledger'
        required: false
        default: '1'
      batchSize:
        description: 'Batch Start Ledger'
        required: false
        default: '30016'
      arraySize:
        description: 'Array Size'
        required: false
        default: '2'
      jobDefinition:
        description: 'Job Definition'
        required: false
        default: 'verify-range-c5-large-job:4'
      jobQueue:
        description: 'Job Queue'
        required: false
        default: 'verfy-range-c5-large-queue'

jobs:
  verifyRangeTestJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
      - name: Install jq
        run: sudo apt-get install jq
      - name: Run verify-range test job
        run: $GITHUB_WORKSPACE/services/horizon/docker/verify-range/run_verify_range_test.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-east-1
          BRANCH: ${{ github.event.inputs.branch }}
          BASE_BRANCH: ${{ github.event.inputs.baseBranch }}
          BATCH_START_LEDGER: ${{ github.event.inputs.batchStartLedger }}
          BATCH_SIZE: ${{ github.event.inputs.batchSize }}
          ARRAY_SIZE: ${{ github.event.inputs.arraySize }}
          JOB_DEFINITION: ${{ github.event.inputs.jobDefinition }}
          JOB_QUEUE: ${{ github.event.inputs.jobQueue }}
